version: '3.7'

db:
    image: postgres
    restart: always
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
        - .:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      ports:
        - "5432:5432"